version: "2"
linters:
  enable:
    # - errorlint
    - misspell
    - modernize
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mdlayher/netlink)
    gofumpt:
      extra:
        group-params: true
    goimports:
      local-prefixes:
        - github.com/mdlayher/netlink
